/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CollateralVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeMarket"
      | "authorizedMarkets"
      | "balances"
      | "collateralToken"
      | "deauthorizeMarket"
      | "deposit"
      | "getAvailableBalance"
      | "getLockedBalance"
      | "lockCollateral"
      | "lockedBalances"
      | "owner"
      | "renounceOwnership"
      | "totalDeposited"
      | "totalLocked"
      | "transferLockedCollateral"
      | "transferOwnership"
      | "unlockCollateral"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralLocked"
      | "CollateralTransferred"
      | "CollateralUnlocked"
      | "Deposited"
      | "MarketAuthorized"
      | "MarketDeauthorized"
      | "OwnershipTransferred"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedMarkets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCollateral",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferLockedCollateral",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCollateral",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferLockedCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CollateralLockedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    market: AddressLike
  ];
  export type OutputTuple = [user: string, amount: bigint, market: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    market: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralTransferredEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    market: AddressLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    market: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    market: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralUnlockedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    market: AddressLike
  ];
  export type OutputTuple = [user: string, amount: bigint, market: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    market: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketAuthorizedEvent {
  export type InputTuple = [market: AddressLike];
  export type OutputTuple = [market: string];
  export interface OutputObject {
    market: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketDeauthorizedEvent {
  export type InputTuple = [market: AddressLike];
  export type OutputTuple = [market: string];
  export interface OutputObject {
    market: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CollateralVault extends BaseContract {
  connect(runner?: ContractRunner | null): CollateralVault;
  waitForDeployment(): Promise<this>;

  interface: CollateralVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeMarket: TypedContractMethod<
    [market: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedMarkets: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  collateralToken: TypedContractMethod<[], [string], "view">;

  deauthorizeMarket: TypedContractMethod<
    [market: AddressLike],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getAvailableBalance: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getLockedBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  lockCollateral: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockedBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalDeposited: TypedContractMethod<[], [bigint], "view">;

  totalLocked: TypedContractMethod<[], [bigint], "view">;

  transferLockedCollateral: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockCollateral: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeMarket"
  ): TypedContractMethod<[market: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedMarkets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deauthorizeMarket"
  ): TypedContractMethod<[market: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAvailableBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLockedBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockCollateral"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockedBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferLockedCollateral"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockCollateral"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CollateralLocked"
  ): TypedContractEvent<
    CollateralLockedEvent.InputTuple,
    CollateralLockedEvent.OutputTuple,
    CollateralLockedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralTransferred"
  ): TypedContractEvent<
    CollateralTransferredEvent.InputTuple,
    CollateralTransferredEvent.OutputTuple,
    CollateralTransferredEvent.OutputObject
  >;
  getEvent(
    key: "CollateralUnlocked"
  ): TypedContractEvent<
    CollateralUnlockedEvent.InputTuple,
    CollateralUnlockedEvent.OutputTuple,
    CollateralUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "MarketAuthorized"
  ): TypedContractEvent<
    MarketAuthorizedEvent.InputTuple,
    MarketAuthorizedEvent.OutputTuple,
    MarketAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "MarketDeauthorized"
  ): TypedContractEvent<
    MarketDeauthorizedEvent.InputTuple,
    MarketDeauthorizedEvent.OutputTuple,
    MarketDeauthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "CollateralLocked(address,uint256,address)": TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;
    CollateralLocked: TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;

    "CollateralTransferred(address,address,uint256,address)": TypedContractEvent<
      CollateralTransferredEvent.InputTuple,
      CollateralTransferredEvent.OutputTuple,
      CollateralTransferredEvent.OutputObject
    >;
    CollateralTransferred: TypedContractEvent<
      CollateralTransferredEvent.InputTuple,
      CollateralTransferredEvent.OutputTuple,
      CollateralTransferredEvent.OutputObject
    >;

    "CollateralUnlocked(address,uint256,address)": TypedContractEvent<
      CollateralUnlockedEvent.InputTuple,
      CollateralUnlockedEvent.OutputTuple,
      CollateralUnlockedEvent.OutputObject
    >;
    CollateralUnlocked: TypedContractEvent<
      CollateralUnlockedEvent.InputTuple,
      CollateralUnlockedEvent.OutputTuple,
      CollateralUnlockedEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "MarketAuthorized(address)": TypedContractEvent<
      MarketAuthorizedEvent.InputTuple,
      MarketAuthorizedEvent.OutputTuple,
      MarketAuthorizedEvent.OutputObject
    >;
    MarketAuthorized: TypedContractEvent<
      MarketAuthorizedEvent.InputTuple,
      MarketAuthorizedEvent.OutputTuple,
      MarketAuthorizedEvent.OutputObject
    >;

    "MarketDeauthorized(address)": TypedContractEvent<
      MarketDeauthorizedEvent.InputTuple,
      MarketDeauthorizedEvent.OutputTuple,
      MarketDeauthorizedEvent.OutputObject
    >;
    MarketDeauthorized: TypedContractEvent<
      MarketDeauthorizedEvent.InputTuple,
      MarketDeauthorizedEvent.OutputTuple,
      MarketDeauthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
