/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { CollateralVault } from "./CollateralVault";
export type { OutcomeToken } from "./OutcomeToken";
export type { PredictionMarket } from "./PredictionMarket";
export type { Tournament } from "./Tournament";
