/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarket {
  export type MarketStruct = {
    marketId: BytesLike;
    question: string;
    yesToken: AddressLike;
    noToken: AddressLike;
    yesSupply: BigNumberish;
    noSupply: BigNumberish;
    totalCollateral: BigNumberish;
    status: BigNumberish;
    winningOutcome: BigNumberish;
    expireTime: BigNumberish;
    createdAt: BigNumberish;
    tournamentOperator: AddressLike;
  };

  export type MarketStructOutput = [
    marketId: string,
    question: string,
    yesToken: string,
    noToken: string,
    yesSupply: bigint,
    noSupply: bigint,
    totalCollateral: bigint,
    status: bigint,
    winningOutcome: bigint,
    expireTime: bigint,
    createdAt: bigint,
    tournamentOperator: string
  ] & {
    marketId: string;
    question: string;
    yesToken: string;
    noToken: string;
    yesSupply: bigint;
    noSupply: bigint;
    totalCollateral: bigint;
    status: bigint;
    winningOutcome: bigint;
    expireTime: bigint;
    createdAt: bigint;
    tournamentOperator: string;
  };

  export type OrderStruct = {
    orderId: BytesLike;
    marketId: BytesLike;
    trader: AddressLike;
    side: BigNumberish;
    outcome: BigNumberish;
    price: BigNumberish;
    quantity: BigNumberish;
    filled: BigNumberish;
    collateralLocked: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    expireTime: BigNumberish;
  };

  export type OrderStructOutput = [
    orderId: string,
    marketId: string,
    trader: string,
    side: bigint,
    outcome: bigint,
    price: bigint,
    quantity: bigint,
    filled: bigint,
    collateralLocked: bigint,
    status: bigint,
    createdAt: bigint,
    expireTime: bigint
  ] & {
    orderId: string;
    marketId: string;
    trader: string;
    side: bigint;
    outcome: bigint;
    price: bigint;
    quantity: bigint;
    filled: bigint;
    collateralLocked: bigint;
    status: bigint;
    createdAt: bigint;
    expireTime: bigint;
  };
}

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "cancelMarket"
      | "cancelOrder"
      | "claimRefund"
      | "claimWinnings"
      | "createMarket"
      | "getMarket"
      | "getMarketIds"
      | "getOrder"
      | "getOrderBook"
      | "getRoleAdmin"
      | "getUserOrders"
      | "grantRole"
      | "hasClaimed"
      | "hasRole"
      | "marketIds"
      | "markets"
      | "minOrderSize"
      | "orderBook"
      | "orders"
      | "pauseMarket"
      | "placeOrder"
      | "renounceRole"
      | "resolveMarket"
      | "resumeMarket"
      | "revokeRole"
      | "setMinOrderSize"
      | "supportsInterface"
      | "userOrders"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "MarketResolved"
      | "MarketStatusChanged"
      | "MinOrderSizeUpdated"
      | "OrderCancelled"
      | "OrderFilled"
      | "OrderPlaced"
      | "RefundClaimed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SharesBurned"
      | "SharesMinted"
      | "Trade"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [BytesLike, string, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketIds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOrder", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOrderBook",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "minOrderSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orderBook",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pauseMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "placeOrder",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinOrderSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "marketIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minOrderSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orderBook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinOrderSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOrders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    question: string,
    yesToken: AddressLike,
    noToken: AddressLike,
    operator: AddressLike,
    expireTime: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    question: string,
    yesToken: string,
    noToken: string,
    operator: string,
    expireTime: bigint
  ];
  export interface OutputObject {
    marketId: string;
    question: string;
    yesToken: string;
    noToken: string;
    operator: string;
    expireTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    winningOutcome: BigNumberish,
    resolver: AddressLike
  ];
  export type OutputTuple = [
    marketId: string,
    winningOutcome: bigint,
    resolver: string
  ];
  export interface OutputObject {
    marketId: string;
    winningOutcome: bigint;
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketStatusChangedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    marketId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinOrderSizeUpdatedEvent {
  export type InputTuple = [oldSize: BigNumberish, newSize: BigNumberish];
  export type OutputTuple = [oldSize: bigint, newSize: bigint];
  export interface OutputObject {
    oldSize: bigint;
    newSize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BytesLike, trader: AddressLike];
  export type OutputTuple = [orderId: string, trader: string];
  export interface OutputObject {
    orderId: string;
    trader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BytesLike,
    filledQuantity: BigNumberish,
    remainingQuantity: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    filledQuantity: bigint,
    remainingQuantity: bigint
  ];
  export interface OutputObject {
    orderId: string;
    filledQuantity: bigint;
    remainingQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderPlacedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    marketId: BytesLike,
    trader: AddressLike,
    side: BigNumberish,
    outcome: BigNumberish,
    price: BigNumberish,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    marketId: string,
    trader: string,
    side: bigint,
    outcome: bigint,
    price: bigint,
    quantity: bigint
  ];
  export interface OutputObject {
    orderId: string;
    marketId: string;
    trader: string;
    side: bigint;
    outcome: bigint;
    price: bigint;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: string, user: string, amount: bigint];
  export interface OutputObject {
    marketId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesBurnedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    holder: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    holder: string,
    yesAmount: bigint,
    noAmount: bigint
  ];
  export interface OutputObject {
    marketId: string;
    holder: string;
    yesAmount: bigint;
    noAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesMintedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    recipient: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    recipient: string,
    yesAmount: bigint,
    noAmount: bigint
  ];
  export interface OutputObject {
    marketId: string;
    recipient: string;
    yesAmount: bigint;
    noAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    fillId: BytesLike,
    marketId: BytesLike,
    makerOrderId: BytesLike,
    takerOrderId: BytesLike,
    matchType: BigNumberish,
    quantity: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    fillId: string,
    marketId: string,
    makerOrderId: string,
    takerOrderId: string,
    matchType: bigint,
    quantity: bigint,
    price: bigint
  ];
  export interface OutputObject {
    fillId: string;
    marketId: string;
    makerOrderId: string;
    takerOrderId: string;
    matchType: bigint;
    quantity: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    user: AddressLike,
    amount: BigNumberish,
    outcome: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    user: string,
    amount: bigint,
    outcome: bigint
  ];
  export interface OutputObject {
    marketId: string;
    user: string;
    amount: bigint;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  cancelMarket: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelOrder: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  claimRefund: TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;

  claimWinnings: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      marketId: BytesLike,
      question: string,
      expireTime: BigNumberish,
      operator: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getMarket: TypedContractMethod<
    [marketId: BytesLike],
    [PredictionMarket.MarketStructOutput],
    "view"
  >;

  getMarketIds: TypedContractMethod<[], [string[]], "view">;

  getOrder: TypedContractMethod<
    [orderId: BytesLike],
    [PredictionMarket.OrderStructOutput],
    "view"
  >;

  getOrderBook: TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish, side: BigNumberish],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUserOrders: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasClaimed: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  marketIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        marketId: string;
        question: string;
        yesToken: string;
        noToken: string;
        yesSupply: bigint;
        noSupply: bigint;
        totalCollateral: bigint;
        status: bigint;
        winningOutcome: bigint;
        expireTime: bigint;
        createdAt: bigint;
        tournamentOperator: string;
      }
    ],
    "view"
  >;

  minOrderSize: TypedContractMethod<[], [bigint], "view">;

  orderBook: TypedContractMethod<
    [
      arg0: BytesLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish
    ],
    [string],
    "view"
  >;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        orderId: string;
        marketId: string;
        trader: string;
        side: bigint;
        outcome: bigint;
        price: bigint;
        quantity: bigint;
        filled: bigint;
        collateralLocked: bigint;
        status: bigint;
        createdAt: bigint;
        expireTime: bigint;
      }
    ],
    "view"
  >;

  pauseMarket: TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;

  placeOrder: TypedContractMethod<
    [
      marketId: BytesLike,
      side: BigNumberish,
      outcome: BigNumberish,
      price: BigNumberish,
      quantity: BigNumberish,
      expireTime: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveMarket: TypedContractMethod<
    [marketId: BytesLike, winningOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  resumeMarket: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinOrderSize: TypedContractMethod<
    [newMinOrderSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  userOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      marketId: BytesLike,
      question: string,
      expireTime: BigNumberish,
      operator: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [PredictionMarket.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [PredictionMarket.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderBook"
  ): TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish, side: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        marketId: string;
        question: string;
        yesToken: string;
        noToken: string;
        yesSupply: bigint;
        noSupply: bigint;
        totalCollateral: bigint;
        status: bigint;
        winningOutcome: bigint;
        expireTime: bigint;
        createdAt: bigint;
        tournamentOperator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "minOrderSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orderBook"
  ): TypedContractMethod<
    [
      arg0: BytesLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        orderId: string;
        marketId: string;
        trader: string;
        side: bigint;
        outcome: bigint;
        price: bigint;
        quantity: bigint;
        filled: bigint;
        collateralLocked: bigint;
        status: bigint;
        createdAt: bigint;
        expireTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pauseMarket"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "placeOrder"
  ): TypedContractMethod<
    [
      marketId: BytesLike,
      side: BigNumberish,
      outcome: BigNumberish,
      price: BigNumberish,
      quantity: BigNumberish,
      expireTime: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [marketId: BytesLike, winningOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resumeMarket"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinOrderSize"
  ): TypedContractMethod<[newMinOrderSize: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "userOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "MarketStatusChanged"
  ): TypedContractEvent<
    MarketStatusChangedEvent.InputTuple,
    MarketStatusChangedEvent.OutputTuple,
    MarketStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "MinOrderSizeUpdated"
  ): TypedContractEvent<
    MinOrderSizeUpdatedEvent.InputTuple,
    MinOrderSizeUpdatedEvent.OutputTuple,
    MinOrderSizeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OrderPlaced"
  ): TypedContractEvent<
    OrderPlacedEvent.InputTuple,
    OrderPlacedEvent.OutputTuple,
    OrderPlacedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SharesBurned"
  ): TypedContractEvent<
    SharesBurnedEvent.InputTuple,
    SharesBurnedEvent.OutputTuple,
    SharesBurnedEvent.OutputObject
  >;
  getEvent(
    key: "SharesMinted"
  ): TypedContractEvent<
    SharesMintedEvent.InputTuple,
    SharesMintedEvent.OutputTuple,
    SharesMintedEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "MarketCreated(bytes32,string,address,address,address,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(bytes32,uint8,address)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "MarketStatusChanged(bytes32,uint8,uint8)": TypedContractEvent<
      MarketStatusChangedEvent.InputTuple,
      MarketStatusChangedEvent.OutputTuple,
      MarketStatusChangedEvent.OutputObject
    >;
    MarketStatusChanged: TypedContractEvent<
      MarketStatusChangedEvent.InputTuple,
      MarketStatusChangedEvent.OutputTuple,
      MarketStatusChangedEvent.OutputObject
    >;

    "MinOrderSizeUpdated(uint256,uint256)": TypedContractEvent<
      MinOrderSizeUpdatedEvent.InputTuple,
      MinOrderSizeUpdatedEvent.OutputTuple,
      MinOrderSizeUpdatedEvent.OutputObject
    >;
    MinOrderSizeUpdated: TypedContractEvent<
      MinOrderSizeUpdatedEvent.InputTuple,
      MinOrderSizeUpdatedEvent.OutputTuple,
      MinOrderSizeUpdatedEvent.OutputObject
    >;

    "OrderCancelled(bytes32,address)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderFilled(bytes32,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OrderPlaced(bytes32,bytes32,address,uint8,uint8,uint256,uint256)": TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;
    OrderPlaced: TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;

    "RefundClaimed(bytes32,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SharesBurned(bytes32,address,uint256,uint256)": TypedContractEvent<
      SharesBurnedEvent.InputTuple,
      SharesBurnedEvent.OutputTuple,
      SharesBurnedEvent.OutputObject
    >;
    SharesBurned: TypedContractEvent<
      SharesBurnedEvent.InputTuple,
      SharesBurnedEvent.OutputTuple,
      SharesBurnedEvent.OutputObject
    >;

    "SharesMinted(bytes32,address,uint256,uint256)": TypedContractEvent<
      SharesMintedEvent.InputTuple,
      SharesMintedEvent.OutputTuple,
      SharesMintedEvent.OutputObject
    >;
    SharesMinted: TypedContractEvent<
      SharesMintedEvent.InputTuple,
      SharesMintedEvent.OutputTuple,
      SharesMintedEvent.OutputObject
    >;

    "Trade(bytes32,bytes32,bytes32,bytes32,uint8,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;

    "WinningsClaimed(bytes32,address,uint256,uint8)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
