/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Tournament {
  export type TournamentInfoStruct = {
    tournamentId: BytesLike;
    name: string;
    game: string;
    operator: AddressLike;
    status: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    createdAt: BigNumberish;
    marketIds: BytesLike[];
    entryFee: BigNumberish;
    totalEntryFees: BigNumberish;
    participantCount: BigNumberish;
  };

  export type TournamentInfoStructOutput = [
    tournamentId: string,
    name: string,
    game: string,
    operator: string,
    status: bigint,
    startTime: bigint,
    endTime: bigint,
    createdAt: bigint,
    marketIds: string[],
    entryFee: bigint,
    totalEntryFees: bigint,
    participantCount: bigint
  ] & {
    tournamentId: string;
    name: string;
    game: string;
    operator: string;
    status: bigint;
    startTime: bigint;
    endTime: bigint;
    createdAt: bigint;
    marketIds: string[];
    entryFee: bigint;
    totalEntryFees: bigint;
    participantCount: bigint;
  };
}

export interface TournamentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "TOURNAMENT_OPERATOR_ROLE"
      | "cancelMarket"
      | "cancelTournament"
      | "collateralToken"
      | "completeTournament"
      | "createMarketForTournament"
      | "createTournament"
      | "getMarketTournament"
      | "getOperatorTournaments"
      | "getRoleAdmin"
      | "getTournament"
      | "getTournamentIds"
      | "getTournamentMarkets"
      | "grantRole"
      | "hasRole"
      | "isParticipant"
      | "isTournamentOperator"
      | "marketToTournament"
      | "minEntryFee"
      | "operatorTournaments"
      | "pauseMarket"
      | "predictionMarket"
      | "registerForTournament"
      | "renounceRole"
      | "resolveMarket"
      | "resumeMarket"
      | "revokeRole"
      | "setMinEntryFee"
      | "startTournament"
      | "supportsInterface"
      | "tournamentIds"
      | "tournaments"
      | "transferOperator"
      | "updateTournamentEntryFee"
      | "withdrawEntryFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntryFeesWithdrawn"
      | "MarketAddedToTournament"
      | "MarketRemovedFromTournament"
      | "MinEntryFeeUpdated"
      | "ParticipantRegistered"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TournamentCreated"
      | "TournamentEntryFeeUpdated"
      | "TournamentOperatorChanged"
      | "TournamentStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOURNAMENT_OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTournament",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeTournament",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketForTournament",
    values: [BytesLike, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTournament",
    values: [
      string,
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketTournament",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperatorTournaments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTournament",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTournamentIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTournamentMarkets",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isParticipant",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTournamentOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketToTournament",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minEntryFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operatorTournaments",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseMarket",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictionMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerForTournament",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeMarket",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinEntryFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startTournament",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tournamentIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tournaments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOperator",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTournamentEntryFee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEntryFees",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOURNAMENT_OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketForTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperatorTournaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTournamentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTournamentMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTournamentOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketToTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minEntryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operatorTournaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictionMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerForTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinEntryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournamentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTournamentEntryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEntryFees",
    data: BytesLike
  ): Result;
}

export namespace EntryFeesWithdrawnEvent {
  export type InputTuple = [
    tournamentId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    tournamentId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketAddedToTournamentEvent {
  export type InputTuple = [
    tournamentId: BytesLike,
    marketId: BytesLike,
    question: string
  ];
  export type OutputTuple = [
    tournamentId: string,
    marketId: string,
    question: string
  ];
  export interface OutputObject {
    tournamentId: string;
    marketId: string;
    question: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketRemovedFromTournamentEvent {
  export type InputTuple = [tournamentId: BytesLike, marketId: BytesLike];
  export type OutputTuple = [tournamentId: string, marketId: string];
  export interface OutputObject {
    tournamentId: string;
    marketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinEntryFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantRegisteredEvent {
  export type InputTuple = [
    tournamentId: BytesLike,
    participant: AddressLike,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: string,
    participant: string,
    entryFee: bigint
  ];
  export interface OutputObject {
    tournamentId: string;
    participant: string;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCreatedEvent {
  export type InputTuple = [
    tournamentId: BytesLike,
    name: string,
    game: string,
    operator: AddressLike,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: string,
    name: string,
    game: string,
    operator: string,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    tournamentId: string;
    name: string;
    game: string;
    operator: string;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentEntryFeeUpdatedEvent {
  export type InputTuple = [
    tournamentId: BytesLike,
    oldFee: BigNumberish,
    newFee: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: string,
    oldFee: bigint,
    newFee: bigint
  ];
  export interface OutputObject {
    tournamentId: string;
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentOperatorChangedEvent {
  export type InputTuple = [
    tournamentId: BytesLike,
    oldOperator: AddressLike,
    newOperator: AddressLike
  ];
  export type OutputTuple = [
    tournamentId: string,
    oldOperator: string,
    newOperator: string
  ];
  export interface OutputObject {
    tournamentId: string;
    oldOperator: string;
    newOperator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentStatusChangedEvent {
  export type InputTuple = [
    tournamentId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    tournamentId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tournament extends BaseContract {
  connect(runner?: ContractRunner | null): Tournament;
  waitForDeployment(): Promise<this>;

  interface: TournamentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  TOURNAMENT_OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  cancelMarket: TypedContractMethod<
    [tournamentId: BytesLike, marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelTournament: TypedContractMethod<
    [tournamentId: BytesLike],
    [void],
    "nonpayable"
  >;

  collateralToken: TypedContractMethod<[], [string], "view">;

  completeTournament: TypedContractMethod<
    [tournamentId: BytesLike],
    [void],
    "nonpayable"
  >;

  createMarketForTournament: TypedContractMethod<
    [
      tournamentId: BytesLike,
      marketId: BytesLike,
      question: string,
      expireTime: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  createTournament: TypedContractMethod<
    [
      name: string,
      game: string,
      operator: AddressLike,
      startTime: BigNumberish,
      endTime: BigNumberish,
      entryFee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getMarketTournament: TypedContractMethod<
    [marketId: BytesLike],
    [string],
    "view"
  >;

  getOperatorTournaments: TypedContractMethod<
    [operator: AddressLike],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTournament: TypedContractMethod<
    [tournamentId: BytesLike],
    [Tournament.TournamentInfoStructOutput],
    "view"
  >;

  getTournamentIds: TypedContractMethod<[], [string[]], "view">;

  getTournamentMarkets: TypedContractMethod<
    [tournamentId: BytesLike],
    [string[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isParticipant: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isTournamentOperator: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  marketToTournament: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  minEntryFee: TypedContractMethod<[], [bigint], "view">;

  operatorTournaments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  pauseMarket: TypedContractMethod<
    [tournamentId: BytesLike, marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  predictionMarket: TypedContractMethod<[], [string], "view">;

  registerForTournament: TypedContractMethod<
    [tournamentId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveMarket: TypedContractMethod<
    [
      tournamentId: BytesLike,
      marketId: BytesLike,
      winningOutcome: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  resumeMarket: TypedContractMethod<
    [tournamentId: BytesLike, marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinEntryFee: TypedContractMethod<
    [newMinEntryFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  startTournament: TypedContractMethod<
    [tournamentId: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tournamentIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  tournaments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tournamentId: string;
        name: string;
        game: string;
        operator: string;
        status: bigint;
        startTime: bigint;
        endTime: bigint;
        createdAt: bigint;
        entryFee: bigint;
        totalEntryFees: bigint;
        participantCount: bigint;
      }
    ],
    "view"
  >;

  transferOperator: TypedContractMethod<
    [tournamentId: BytesLike, newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTournamentEntryFee: TypedContractMethod<
    [tournamentId: BytesLike, newEntryFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawEntryFees: TypedContractMethod<
    [tournamentId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TOURNAMENT_OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<
    [tournamentId: BytesLike, marketId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTournament"
  ): TypedContractMethod<[tournamentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeTournament"
  ): TypedContractMethod<[tournamentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarketForTournament"
  ): TypedContractMethod<
    [
      tournamentId: BytesLike,
      marketId: BytesLike,
      question: string,
      expireTime: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTournament"
  ): TypedContractMethod<
    [
      name: string,
      game: string,
      operator: AddressLike,
      startTime: BigNumberish,
      endTime: BigNumberish,
      entryFee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarketTournament"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getOperatorTournaments"
  ): TypedContractMethod<[operator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTournament"
  ): TypedContractMethod<
    [tournamentId: BytesLike],
    [Tournament.TournamentInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTournamentIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTournamentMarkets"
  ): TypedContractMethod<[tournamentId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isParticipant"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTournamentOperator"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "marketToTournament"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "minEntryFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operatorTournaments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pauseMarket"
  ): TypedContractMethod<
    [tournamentId: BytesLike, marketId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "predictionMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerForTournament"
  ): TypedContractMethod<[tournamentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [
      tournamentId: BytesLike,
      marketId: BytesLike,
      winningOutcome: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resumeMarket"
  ): TypedContractMethod<
    [tournamentId: BytesLike, marketId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinEntryFee"
  ): TypedContractMethod<[newMinEntryFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startTournament"
  ): TypedContractMethod<[tournamentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tournamentIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tournaments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tournamentId: string;
        name: string;
        game: string;
        operator: string;
        status: bigint;
        startTime: bigint;
        endTime: bigint;
        createdAt: bigint;
        entryFee: bigint;
        totalEntryFees: bigint;
        participantCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOperator"
  ): TypedContractMethod<
    [tournamentId: BytesLike, newOperator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTournamentEntryFee"
  ): TypedContractMethod<
    [tournamentId: BytesLike, newEntryFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawEntryFees"
  ): TypedContractMethod<
    [tournamentId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EntryFeesWithdrawn"
  ): TypedContractEvent<
    EntryFeesWithdrawnEvent.InputTuple,
    EntryFeesWithdrawnEvent.OutputTuple,
    EntryFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MarketAddedToTournament"
  ): TypedContractEvent<
    MarketAddedToTournamentEvent.InputTuple,
    MarketAddedToTournamentEvent.OutputTuple,
    MarketAddedToTournamentEvent.OutputObject
  >;
  getEvent(
    key: "MarketRemovedFromTournament"
  ): TypedContractEvent<
    MarketRemovedFromTournamentEvent.InputTuple,
    MarketRemovedFromTournamentEvent.OutputTuple,
    MarketRemovedFromTournamentEvent.OutputObject
  >;
  getEvent(
    key: "MinEntryFeeUpdated"
  ): TypedContractEvent<
    MinEntryFeeUpdatedEvent.InputTuple,
    MinEntryFeeUpdatedEvent.OutputTuple,
    MinEntryFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantRegistered"
  ): TypedContractEvent<
    ParticipantRegisteredEvent.InputTuple,
    ParticipantRegisteredEvent.OutputTuple,
    ParticipantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentCreated"
  ): TypedContractEvent<
    TournamentCreatedEvent.InputTuple,
    TournamentCreatedEvent.OutputTuple,
    TournamentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentEntryFeeUpdated"
  ): TypedContractEvent<
    TournamentEntryFeeUpdatedEvent.InputTuple,
    TournamentEntryFeeUpdatedEvent.OutputTuple,
    TournamentEntryFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentOperatorChanged"
  ): TypedContractEvent<
    TournamentOperatorChangedEvent.InputTuple,
    TournamentOperatorChangedEvent.OutputTuple,
    TournamentOperatorChangedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentStatusChanged"
  ): TypedContractEvent<
    TournamentStatusChangedEvent.InputTuple,
    TournamentStatusChangedEvent.OutputTuple,
    TournamentStatusChangedEvent.OutputObject
  >;

  filters: {
    "EntryFeesWithdrawn(bytes32,address,uint256)": TypedContractEvent<
      EntryFeesWithdrawnEvent.InputTuple,
      EntryFeesWithdrawnEvent.OutputTuple,
      EntryFeesWithdrawnEvent.OutputObject
    >;
    EntryFeesWithdrawn: TypedContractEvent<
      EntryFeesWithdrawnEvent.InputTuple,
      EntryFeesWithdrawnEvent.OutputTuple,
      EntryFeesWithdrawnEvent.OutputObject
    >;

    "MarketAddedToTournament(bytes32,bytes32,string)": TypedContractEvent<
      MarketAddedToTournamentEvent.InputTuple,
      MarketAddedToTournamentEvent.OutputTuple,
      MarketAddedToTournamentEvent.OutputObject
    >;
    MarketAddedToTournament: TypedContractEvent<
      MarketAddedToTournamentEvent.InputTuple,
      MarketAddedToTournamentEvent.OutputTuple,
      MarketAddedToTournamentEvent.OutputObject
    >;

    "MarketRemovedFromTournament(bytes32,bytes32)": TypedContractEvent<
      MarketRemovedFromTournamentEvent.InputTuple,
      MarketRemovedFromTournamentEvent.OutputTuple,
      MarketRemovedFromTournamentEvent.OutputObject
    >;
    MarketRemovedFromTournament: TypedContractEvent<
      MarketRemovedFromTournamentEvent.InputTuple,
      MarketRemovedFromTournamentEvent.OutputTuple,
      MarketRemovedFromTournamentEvent.OutputObject
    >;

    "MinEntryFeeUpdated(uint256,uint256)": TypedContractEvent<
      MinEntryFeeUpdatedEvent.InputTuple,
      MinEntryFeeUpdatedEvent.OutputTuple,
      MinEntryFeeUpdatedEvent.OutputObject
    >;
    MinEntryFeeUpdated: TypedContractEvent<
      MinEntryFeeUpdatedEvent.InputTuple,
      MinEntryFeeUpdatedEvent.OutputTuple,
      MinEntryFeeUpdatedEvent.OutputObject
    >;

    "ParticipantRegistered(bytes32,address,uint256)": TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;
    ParticipantRegistered: TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TournamentCreated(bytes32,string,string,address,uint256,uint256)": TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;
    TournamentCreated: TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;

    "TournamentEntryFeeUpdated(bytes32,uint256,uint256)": TypedContractEvent<
      TournamentEntryFeeUpdatedEvent.InputTuple,
      TournamentEntryFeeUpdatedEvent.OutputTuple,
      TournamentEntryFeeUpdatedEvent.OutputObject
    >;
    TournamentEntryFeeUpdated: TypedContractEvent<
      TournamentEntryFeeUpdatedEvent.InputTuple,
      TournamentEntryFeeUpdatedEvent.OutputTuple,
      TournamentEntryFeeUpdatedEvent.OutputObject
    >;

    "TournamentOperatorChanged(bytes32,address,address)": TypedContractEvent<
      TournamentOperatorChangedEvent.InputTuple,
      TournamentOperatorChangedEvent.OutputTuple,
      TournamentOperatorChangedEvent.OutputObject
    >;
    TournamentOperatorChanged: TypedContractEvent<
      TournamentOperatorChangedEvent.InputTuple,
      TournamentOperatorChangedEvent.OutputTuple,
      TournamentOperatorChangedEvent.OutputObject
    >;

    "TournamentStatusChanged(bytes32,uint8,uint8)": TypedContractEvent<
      TournamentStatusChangedEvent.InputTuple,
      TournamentStatusChangedEvent.OutputTuple,
      TournamentStatusChangedEvent.OutputObject
    >;
    TournamentStatusChanged: TypedContractEvent<
      TournamentStatusChangedEvent.InputTuple,
      TournamentStatusChangedEvent.OutputTuple,
      TournamentStatusChangedEvent.OutputObject
    >;
  };
}
